In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import cross_val_score


In [2]:
X=pd.read_csv("X_physio_scaled.csv")

In [3]:
y=pd.read_csv("y_physio.csv")

In [4]:
X.head()

Age    Gender     Place       Qua  F_Income   H_Issue  Alp_Before  \
0  0.176915 -1.014128  0.281474 -0.999376 -0.676596 -1.414485   -3.506268   
1  0.402466 -1.014128  0.518462 -0.999376 -0.358506 -1.414485    0.567371   
2  0.176915 -1.014128 -1.614436 -0.999376  1.974151  1.373653    0.567371   
3  0.222025 -1.014128  0.597458  0.279313 -0.146447  0.301293    0.567371   
4 -0.905728 -1.014128  0.281474 -0.999376  0.913852  0.944709    0.567371   

     D_Al_W  Aware_Ph  Rely_Phy   Phy_Bef   Phy_Eff   Why_Phy   Trv_Iss  
0 -1.050484  0.531767  0.877755  1.173111  1.410705  0.247996 -1.038829  
1  0.564898  0.531767  0.877755  1.173111  1.410705 -1.002006 -1.038829  
2  0.564898  0.531767  0.877755  1.173111  1.410705 -1.002006 -1.038829  
3  1.372589  0.531767 -1.472871  1.173111 -1.559513  1.497999  0.962622  
4  1.372589  0.531767 -1.472871  1.173111 -1.559513  1.497999  0.962622

In [5]:
X.shape

(499, 14)

In [6]:
y.head()

Pref_Phy
0         1
1         1
2         1
3         0
4         0

In [7]:
y.shape

(499, 1)

# ################################################

In [8]:
classifiers = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "K-Nearest Neighbors": KNeighborsClassifier(n_neighbors=3,p=1),
    "Naive Bayes": GaussianNB(),
    "Support Vector Machine": SVC()}

In [9]:
model1=classifiers["Logistic Regression"]
model2=classifiers["Decision Tree"]
model3=classifiers["Random Forest"]
model4=classifiers["K-Nearest Neighbors"]
model5=classifiers["Naive Bayes"]
model6=classifiers["Support Vector Machine"]

In [10]:
cross_val_score_lr=cross_val_score(model1,X,y,cv=5)

C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [11]:
print(cross_val_score_lr)
mean_accuracy_lr=sum(cross_val_score_lr)/len(cross_val_score_lr)
mean_accuracy_lr=mean_accuracy_lr*100
print(mean_accuracy_lr)
m=round(mean_accuracy_lr,2)
print("Accuracy for Logistic Regression with Cross validation Technique is",m)


[0.81       0.8        0.81       0.8        0.80808081]
80.56161616161616
Accuracy for Logistic Regression with Cross validation Technique is 80.56


# ####################################################

In [12]:
cross_val_score_Deci=cross_val_score(model2,X,y,cv=5)

In [13]:
print(cross_val_score_Deci)
mean_accuracy_Deci=sum(cross_val_score_Deci)/len(cross_val_score_Deci)
mean_accuracy_Deci=mean_accuracy_Deci*100
print(mean_accuracy_Deci)
n=round(mean_accuracy_Deci,2)
print("Accuracy for Decision Tree with Cross validation Technique is",n)


[1.         0.99       1.         0.99       0.96969697]
98.9939393939394
Accuracy for Decision Tree with Cross validation Technique is 98.99


# #################################################

In [14]:
cross_val_score_Rand=cross_val_score(model3,X,y,cv=5)

C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:680: DataConversionWarning: A column-vector y wa

In [15]:
print(cross_val_score_Rand)
mean_accuracy_Rand=sum(cross_val_score_Rand)/len(cross_val_score_Rand)
mean_accuracy_Rand=mean_accuracy_Rand*100
print(mean_accuracy_Rand)
p=round(mean_accuracy_Rand,2)
print("Accuracy for Random Forest with Cross validation Technique is",p)

[1. 1. 1. 1. 1.]
100.0
Accuracy for Random Forest with Cross validation Technique is 100.0


# ###################################################

In [16]:
cross_val_score_KNear=cross_val_score(model4,X,y,cv=5)

C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

In [17]:
print(cross_val_score_KNear)
mean_accuracy_KNear=sum(cross_val_score_KNear)/len(cross_val_score_KNear)
mean_accuracy_KNear=mean_accuracy_KNear*100
print(mean_accuracy_KNear)
q=round(mean_accuracy_KNear,2)
print("Accuracy for KNearest Neighbors with Cross validation Technique is",q)

[1. 1. 1. 1. 1.]
100.0
Accuracy for KNearest Neighbors with Cross validation Technique is 100.0


In [18]:
print(model4.get_params())

{'algorithm': 'auto', 'leaf_size': 30, 'metric': 'minkowski', 'metric_params': None, 'n_jobs': None, 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'}


# ##################################################

In [19]:
cross_val_score_Naive=cross_val_score(model5,X,y,cv=5)

C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [20]:
print(cross_val_score_Naive)
mean_accuracy_Naive=sum(cross_val_score_Naive)/len(cross_val_score_Naive)
mean_accuracy_Naive=mean_accuracy_Naive*100
print(mean_accuracy_Naive)
q=round(mean_accuracy_Naive,2)
print("Accuracy for Naive Bayes with Cross validation Technique is",q)


[0.81       0.81       0.81       0.8        0.80808081]
80.76161616161616
Accuracy for Naive Bayes with Cross validation Technique is 80.76


# ##################################################

In [21]:
cross_val_score_SVM=cross_val_score(model6,X,y,cv=5)

C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [22]:
print(cross_val_score_SVM)
mean_accuracy_SVM=sum(cross_val_score_SVM)/len(cross_val_score_SVM)
mean_accuracy_SVM=mean_accuracy_SVM*100
print(mean_accuracy_SVM)
r=round(mean_accuracy_SVM,2)
print("Accuracy for SVM with Cross validation Technique is",r)

[0.99       1.         0.99       0.99       0.97979798]
98.99595959595959
Accuracy for SVM with Cross validation Technique is 99.0


# CONCLUSION

# RANDOM FOREST IS THE BEST MODEL WITH AN ACCURACY OF 100% FOR THIS DATASET

# ###############################################

In [23]:
# CLASSIFICATION REPORTS
# lINEAR REGRESSION
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score, cross_val_predict

In [24]:
y_pred = cross_val_predict(model1, X,y, cv=5)
report=classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.79      0.81      0.80       240
           1       0.82      0.80      0.81       259

    accuracy                           0.81       499
   macro avg       0.81      0.81      0.81       499
weighted avg       0.81      0.81      0.81       499



C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

# #######################################################

In [25]:
# CLASSIFICATION REPORTS
# DECISION TREE CLASSIFIER
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score, cross_val_predict

In [26]:
y_pred=cross_val_predict(model2,X,y,cv=5)
report=classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       240
           1       0.99      0.99      0.99       259

    accuracy                           0.99       499
   macro avg       0.99      0.99      0.99       499
weighted avg       0.99      0.99      0.99       499



# #########################################################

In [27]:
# CLASSIFICATION REPORTS
# RANDOM FOREST
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score, cross_val_predict
y_pred=cross_val_predict(model3,X,y,cv=5)
report=classification_report(y,y_pred)
print(report)


C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  estimator.fit(X_train, y_train, **fit_params)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:1044: DataConversionWarning: A column-vector 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       240
           1       1.00      1.00      1.00       259

    accuracy                           1.00       499
   macro avg       1.00      1.00      1.00       499
weighted avg       1.00      1.00      1.00       499



# ####################################################

In [28]:
# CLASSIFICATION REPORTS
# K NEAREST NEIGHBOUR
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score, cross_val_predict
y_pred=cross_val_predict(model4,X,y,cv=5)
report=classification_report(y,y_pred)
print(report)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00       240
           1       1.00      1.00      1.00       259

    accuracy                           1.00       499
   macro avg       1.00      1.00      1.00       499
weighted avg       1.00      1.00      1.00       499



C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

# ####################################################

In [29]:
# CLASSIFICATION REPORTS
# K NEAREST NEIGHBOUR
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score, cross_val_predict
y_pred=cross_val_predict(model4,X,y,cv=5)
report=classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       240
           1       1.00      1.00      1.00       259

    accuracy                           1.00       499
   macro avg       1.00      1.00      1.00       499
weighted avg       1.00      1.00      1.00       499



C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_sam

# #######################################################

In [30]:
# CLASSIFICATION REPORTS
# NAIVE BAYES
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_score, cross_val_predict
y_pred=cross_val_predict(model5,X,y,cv=5)
report=classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.80      0.80      0.80       240
           1       0.82      0.81      0.81       259

    accuracy                           0.81       499
   macro avg       0.81      0.81      0.81       499
weighted avg       0.81      0.81      0.81       499



C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

# ##################################################

In [31]:
# CLASSIFICATION REPORTS
# K NEAREST NEIGHBOUR
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict
y_pred=cross_val_predict(model6,X,y,cv=5)
report=classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       240
           1       0.98      1.00      0.99       259

    accuracy                           0.99       499
   macro avg       0.99      0.99      0.99       499
weighted avg       0.99      0.99      0.99       499



C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [32]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y,y_pred)
print(cm)


[[235   5]
 [  0 259]]


In [33]:
# CLASSIFICATION REPORTS
# K NEAREST NEIGHBOUR
from sklearn.metrics import classification_report,confusion_matrix
from sklearn.model_selection import cross_val_score, cross_val_predict
y_pred=cross_val_predict(model6,X,y,cv=5)
report=classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       240
           1       0.98      1.00      0.99       259

    accuracy                           0.99       499
   macro avg       0.99      0.99      0.99       499
weighted avg       0.99      0.99      0.99       499



C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Pattu\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), 

In [34]:
494/499

0.9899799599198397

In [35]:
259/259

1.0

In [36]:
235/240

0.9791666666666666

In [37]:
y.value_counts()

Pref_Phy
1           259
0           240
dtype: int64

In [38]:
259/264

0.9810606060606061

In [39]:
235/235

1.0

In [40]:
235/240

0.9791666666666666

In [41]:
259/259

1.0

In [42]:
235/259

0.9073359073359073